### App Request
GET http://localhost:3000/

### Message id
GET http://localhost:3000/messages/6

### Tous les Messages
GET http://localhost:3000/messages

### Post User
POST http://localhost:3000/users
Content-Type: application/json

{
"userName": "Gerard",
"userPassword": "123123",
"userId": "123456789"
}

### Auth Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
"userName": "Gerard",
"userPassword": "123123"
}

### Auth Get Profile [Middleware, Guard test]
GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMjM0NTY3ODkiLCJpYXQiOjE3NDg0NjIzMjUsImV4cCI6MTc0OTc1ODMyNX0.zK0_pt7BW8IRPgh-bZ8qKH2W71ibwcBRVoqZdOxjOWc